- name: Link Snapshot mb_ansible_demo
  hosts: localhost
  collections: dellemc.powermax
  connection: local
  gather_facts: no

  vars_files:
    - uni_connection_vars.yml

  vars:

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{ username }}"
      verifycert: "{{ verifycert }}"

  tasks:
  - name: Change Snapshot Link Status to Linked
    dellemc_powermax_snapshot:
      <<: *uni_connection_vars
      sg_name: "{{sg_name}}"
      snapshot_name: "{{snap_name}}"
      generation: 0
      target_sg_name: "{{tgt_sg}}"
      link_status: "linked"
      state: "present"
