- name: Protect mb_ansible_demo with Replication Synchronous, Asynchronous or Active
  hosts: localhost
  collections: dellemc.powermax
  connection: local
  gather_facts: no

  vars_files:
    - get_password.yml
    - uni_connection_vars.yml

  vars:

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ powermax_password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{ powermax_username }}"
      verifycert: "{{ verifycert }}"

  tasks:
  - name: Protect storagegroup with Replication
    dellemc_powermax_srdf:
      <<: *uni_connection_vars
      sg_name: "{{sg_name}}"
      remote_serial_no: "{{remote_serial_no}}"
      state: 'present'
      srdf_mode: "{{srdf_mode}}"
      wait_for_completion: True
      srdf_state: 'Establish'
