- name: Create a Snapshot for mb_ansible_demo
  hosts: localhost
  collections: dellemc.powermax
  connection: local
  gather_facts: no

  vars_files:
    - uni_connection_vars.yml

  vars:

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{ username }}"
      verifycert: "{{ verifycert }}"

  tasks:
  - name: Create a Snapshot for a Storage Group
    dellemc_powermax_snapshot:
      <<: *uni_connection_vars
      sg_name: "{{sg_name}}"
      snapshot_name: "{{snap_name}}"
      ttl: "{{ttl}}"
      ttl_unit: "{{ttl_unit}}"
      state: "present"
